# PIPELINE DEFINITION
# Name: fraud-model-training
# Description: Feast features -> temporal split -> logistic regression -> MLflow registry -> gate
# Inputs:
#    min_lift: float [Default: 2.0]
components:
  comp-quality-gate:
    executorLabel: exec-quality-gate
    inputDefinitions:
      parameters:
        min_lift:
          parameterType: NUMBER_DOUBLE
        run_id:
          parameterType: STRING
        summary_root:
          parameterType: STRING
  comp-train-and-register:
    executorLabel: exec-train-and-register
    inputDefinitions:
      parameters:
        run_id:
          parameterType: STRING
        summary_root:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-quality-gate:
      container:
        args:
        - '{{$.inputs.parameters[''summary_root'']}}'
        - '{{$.inputs.parameters[''run_id'']}}'
        - '{{$.inputs.parameters[''min_lift'']}}'
        command:
        - sh
        - -c
        - python -m ml.gate --summary-uri "$0/$1/summary.json" --min-lift "$2"
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow.ml-ns.svc.cluster.local:5000
        image: northamerica-northeast1-docker.pkg.dev/aide-playground/insurance-images/training:0.1.4
        resources:
          cpuRequest: 0.2
          memoryRequest: 0.536870912
          resourceCpuRequest: 200m
          resourceMemoryRequest: 512Mi
    exec-train-and-register:
      container:
        args:
        - '{{$.inputs.parameters[''summary_root'']}}'
        - '{{$.inputs.parameters[''run_id'']}}'
        command:
        - sh
        - -c
        - python -m ml.train --summary-uri "$0/$1/summary.json"
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow.ml-ns.svc.cluster.local:5000
        - name: LAKEHOUSE_ROOT
          value: gs://aide-playground-lakehouse
        - name: FEAST_REPO_PATH
          value: /feature_store
        image: northamerica-northeast1-docker.pkg.dev/aide-playground/insurance-images/training:0.1.4
        resources:
          cpuLimit: 2.0
          cpuRequest: 1.0
          memoryLimit: 4.294967296
          memoryRequest: 3.221225472
          resourceCpuLimit: '2'
          resourceCpuRequest: '1'
          resourceMemoryLimit: 4Gi
          resourceMemoryRequest: 3Gi
pipelineInfo:
  description: Feast features -> temporal split -> logistic regression -> MLflow registry
    -> gate
  name: fraud-model-training
root:
  dag:
    tasks:
      quality-gate:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-quality-gate
        dependentTasks:
        - train-and-register
        inputs:
          parameters:
            min_lift:
              componentInputParameter: min_lift
            run_id:
              runtimeValue:
                constant: '{{$.pipeline_job_uuid}}'
            summary_root:
              runtimeValue:
                constant: gs://aide-playground-lakehouse/mlflow/pipelines
        taskInfo:
          name: quality-gate
      train-and-register:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-and-register
        inputs:
          parameters:
            run_id:
              runtimeValue:
                constant: '{{$.pipeline_job_uuid}}'
            summary_root:
              runtimeValue:
                constant: gs://aide-playground-lakehouse/mlflow/pipelines
        retryPolicy:
          backoffDuration: 0s
          backoffFactor: 2.0
          backoffMaxDuration: 3600s
        taskInfo:
          name: train-and-register
  inputDefinitions:
    parameters:
      min_lift:
        defaultValue: 2.0
        isOptional: true
        parameterType: NUMBER_DOUBLE
schemaVersion: 2.1.0
sdkVersion: kfp-2.17.0
