##
# mlflow — tracking server + model registry, ml-ns. Local chart.
##
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd-ns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:qmai7/insurance_ai_de_engineering_project.git
    targetRevision: main_empty
    path: charts/mlflow
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
