apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  type: {{ .Values.service.type }}
  selector:
    app: clickhouse
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: native
      port: {{ .Values.service.nativePort }}
      targetPort: native
