apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mlflow
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
