apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    component: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      enableServiceLinks: false
      containers:
        - name: taskmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["taskmanager"]
          env:
            - name: FLINK_PROPERTIES
              value: |
{{ include "flink.properties" . | indent 16 }}
          ports:
            - name: rpc
              containerPort: 6122
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
{{ toYaml .Values.taskmanager.resources | indent 12 }}
